# -*- coding: utf-8 -*-
"""Thesis_code_7_04_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExzPcte5J5Do6EmAnyIvLI9_j9FU22yV

**Python code used in the paper "Black Shells at the Edge of Collapse"**

A few notes to users:


*   This code's been built in Google Colab; it will need to be modified slightly for other python environments in order to make the samples avaiable to the neural net.
*   If the file containing the samples is stored in Google Drive, then no changes are necessary.
*   Based on where the samples are stored (if not in Google Drive), the directory which currently points to the Google directory (AW_DIR   = "/content/drive/My Drive/sims_mix"), will need to be modified.
"""

# ============================================================
# Run this first: not all packages are used
# ============================================================

import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator, FormatStrFormatter, ScalarFormatter
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import shap
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import os
from sklearn.exceptions import DataDimensionalityWarning

import torch
torch.cuda.empty_cache
torch.cuda.empty_cache()

plt.rcParams['mathtext.fontset'] = 'cm'
plt.rcParams['font.family'] = 'STIXGeneral'

"""**Neural Operators**"""

!pip install neuraloperator
!pip install --quiet SALib

# =======================================================================================================================================================
# Run this code to upload the simulation samples. The samples are produced using the Mathematica notebook; saved in Google Drive, then uploaded here.
# The paper "Black Shells on the Edge of Collapse uses 40,000 samples; however, for testing purposes, 1000 samples should suffice to reduce memeory usage.
# The Mathematica code can be used to generate more samples.
# =======================================================================================================================================================

# merge_1000.py  –  keep both stable (0) and unstable (1) but
#                         drop any run containing NaN/Inf/overflow
import h5py, numpy as np, glob, os, tqdm

RAW_DIR   = "/content/drive/My Drive/sims_mix"   #sims_mix is the name of the file in Google Drive containing the samples.
MASTER_H5 = "master_1000.h5"
raw_files = sorted(glob.glob(os.path.join(RAW_DIR, "sim_*.h5")))

# ---------- stability-test helper: these functions implement the stability tests used in Mathematica -------------------
def stability_flag(state, t, tau_u, tau_axi, slope_eps=1e-8):
    """
    Returns 0 = stable, 1 = unstable  (plus details if required).
    Implements my four Mathematica tests.
    """
    R, *_, m = state
    comp   = m / R
    dt     = np.mean(np.diff(t))

    # derivative with masking
    c_dot  = np.diff(comp, prepend=comp[0]) / dt
    clean  = np.where(np.abs(c_dot) < slope_eps, 0.0, c_dot)

    # --- 1. monotone-slope test ------------------------------------
    win_mono   = 2 * tau_axi
    steps_mono = max(2, int(round(win_mono / dt)))
    signs      = np.sign(clean)
    seg_starts = np.where(np.diff(signs)!=0)[0] + 1
    segs       = np.split(np.column_stack([t, clean]), seg_starts)
    mono_bad   = any(seg[0,1]!=0 and len(seg)>=steps_mono for seg in segs)

    # --- 2. envelope test ------------------------------------------
    win_env    = 2 * tau_u
    steps_env  = max(2, int(round(win_env / dt)))
    half_range = lambda i: 0.5*(comp[max(0,i-steps_env+1):i+1].max() -
                                comp[max(0,i-steps_env+1):i+1].min())
    env_amp    = np.array([half_range(i) for i in range(len(comp))])
    env_bad    = np.any(env_amp > 0.01 * comp[0])

    # --- 3. hi-frequency sign-flip test ----------------------------
    win_flip   = 2 * tau_axi
    steps_flip = max(2, int(round(win_flip / dt)))
    cross_thr  = 4
    flip_counts= [
        np.sum(signs[i:i+steps_flip-1] * signs[i+1:i+steps_flip] < 0)
        for i in range(len(signs)-steps_flip+1)
    ]
    flip_bad   = max(flip_counts) >= cross_thr

    # --- 4. sustained drift test -----------------------------------
    dev_thr    = 0.02 * comp[0]
    win_dev    = 2 * tau_axi
    steps_dev  = max(2, int(round(win_dev / dt)))
    drift_mask = (np.abs(comp - comp[0]) > dev_thr).astype(int)
    drift_sum  = np.convolve(drift_mask, np.ones(steps_dev,int), 'valid')
    drift_bad  = np.any(drift_sum == steps_dev)

    unstable = mono_bad or env_bad or flip_bad or drift_bad
    return int(unstable)
# --------------------------------------------------------------------

# ---------- discover time grid from first file ---------------------
with h5py.File(raw_files[0], "r") as f0:
    grid = f0["/t"][:]
nGrid = len(grid)
print("time grid: ", nGrid)
# ---------- prepare extendible datasets (no pre-count needed) ------
with h5py.File(MASTER_H5, "w") as H:
    d_params = H.create_dataset("params", shape=(0, 3),  maxshape=(None, 3),
                                dtype="float32", compression="gzip")
    d_state  = H.create_dataset("state",  shape=(0, 7, nGrid),
                                maxshape=(None, 7, nGrid),
                                dtype="float32", compression="gzip",
                                chunks=(1, 7, nGrid))
    d_label  = H.create_dataset("label",  shape=(0,), maxshape=(None,),
                                dtype="uint8")
    H.create_dataset("t", data=grid)

    row = 0
    for path in tqdm.tqdm(raw_files, desc="merge"):
        with h5py.File(path, "r") as f:
            p_full = f["/params"][:]
            state  = f["/state"][:]

        # ---- numeric sanity: skip if NaN / Inf / overflow -----------
        if (not np.isfinite(state).all() or
            (np.abs(state) > np.finfo("float32").max).any()):
            continue                         # drop this trajectory

        # ---- compute stability label --------------------------------
        tau_u, tau_axi = p_full[4], p_full[8]
        lbl            = stability_flag(state, grid, tau_u, tau_axi)

        # ---- append to datasets -------------------------------------
        d_params.resize(row+1, axis=0)
        d_state.resize(row+1,  axis=0)
        d_label.resize(row+1,  axis=0)

        d_params[row] = p_full[1:4]          # α, β, ζ₀
        d_state[row]  = state.astype("float32")
        d_label[row]  = lbl
        row += 1

print(f"✓ kept {row} simulations (removed {len(raw_files)-row} corrupted)")
print("✓ wrote", MASTER_H5)

import h5py, numpy as np

with h5py.File("master_1000.h5", "r") as H:
    lbl = H["label"][:]

n_stable   = np.count_nonzero(lbl == 0)
n_unstable = np.count_nonzero(lbl == 1)

print("stable   =", n_stable)
print("unstable =", n_unstable)

# ============================================================
# Split the samples into training, val, and test
# ============================================================

import h5py, numpy as np, matplotlib.pyplot as plt
import torch, random

MASTER_H5 = "master_1000.h5"

# ---------- load once ----------
with h5py.File(MASTER_H5, "r+") as H:          # r+ so we can add datasets
    params = H["params"][:]                    # (N, 3)
    t      = H["t"][:]
    state  = H["state"][:]                     # (N, 7, nGrid)
    labels = H["label"][:]

# ---------- 1. sanity plot ----------
N = len(params)
idx = random.randrange(N)

R, V, rho_g, rho_t, rho_s, T, m = state[idx]
compactness = m / R

plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.plot(t, R, label="R(t)")
#plt.plot(t, m, label="(t)")
plt.xlabel("t"); plt.grid(True); plt.legend()

plt.subplot(1,2,2)
plt.plot(t, compactness)
plt.xlabel("t"); plt.ylabel("m/R"); plt.grid(True)
plt.suptitle(f"sample #{idx}   label={labels[idx]}\nα={params[idx,0]:.4f}  β={params[idx,1]:.4f}  ζ0={params[idx,2]:.4f}")
plt.tight_layout()
plt.show()

# ---------- 2. reproducible split ----------
rng = np.random.default_rng(seed=42)
indices = rng.permutation(N)

train_end = int(0.95 * N)
val_end   = int(0.97 * N)

idx_train = indices[:train_end]
idx_val   = indices[train_end:val_end]
idx_test  = indices[val_end:]

print(f"train / val / test sizes: {len(idx_train)}  {len(idx_val)}  {len(idx_test)}")

# ---------- store the split (only if not already present) ----------
with h5py.File(MASTER_H5, "r+") as H:
    for name, arr in [("idx_train", idx_train),
                      ("idx_val",   idx_val),
                      ("idx_test",  idx_test)]:
        if name in H:
            del H[name]          # overwrite if you re-run
        H.create_dataset(name, data=arr, compression="gzip")

print("✓ split indices saved inside", MASTER_H5)

# ============================================================
# A simple classification MLP
# ============================================================

# ============================================================
# 0.  imports & device
# ============================================================
import h5py, numpy as np, torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import confusion_matrix, f1_score
import seaborn as sns, matplotlib.pyplot as plt

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("using", DEVICE)

MASTER_H5 = "master_1000.h5"

# ============================================================
# 1.  load features, labels
# ============================================================
with h5py.File(MASTER_H5, "r+") as H:
    X = H["params"][:]                    # (N, 3)  α β ζ₀
    y = H["label"][:].astype("int64")     # (N,)

    # if split indices are missing, create them reproducibly
    if not all(name in H for name in ("idx_train","idx_val","idx_test")):
        N = len(y); rng = np.random.default_rng(seed=42)
        idx = rng.permutation(N)
        tr, va = int(.7*N), int(.85*N)
        H.create_dataset("idx_train", data=idx[:tr])
        H.create_dataset("idx_val",   data=idx[tr:va])
        H.create_dataset("idx_test",  data=idx[va:])
        print("• created split indices in file")

    idx_train = H["idx_train"][:]
    idx_val   = H["idx_val"][:]
    idx_test  = H["idx_test"][:]

print("class balance  (0=stable, 1=unstable)")
unique, counts = np.unique(y, return_counts=True)
print(dict(zip(unique, counts)))

# tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

dl = lambda idx, bs, shuffle=False: DataLoader(
        TensorDataset(X[idx], y[idx]), batch_size=bs, shuffle=shuffle)

train_dl = dl(idx_train, 64, True)
val_dl   = dl(idx_val,   32)
test_dl  = dl(idx_test,  32)

# ============================================================
# 2.  simple 3-layer MLP
# ============================================================
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(3, 128), nn.ReLU(),
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, 2)
        )
    def forward(self, x): return self.net(x)

model = MLP().to(DEVICE)
opt   = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()

# helpers
def batch_acc(dl):
    model.eval(); correct=tot=0
    with torch.no_grad():
        for xb,yb in dl:
            p = model(xb.to(DEVICE)).argmax(1).cpu()
            correct += (p==yb).sum().item(); tot += len(yb)
    return correct / tot

best_val = 0; patience=1000; wait=0; best_state=None

# ============================================================
# 3.  training loop with early-stop
# ============================================================
for epoch in range(200):
    model.train()
    for xb,yb in train_dl:
        xb,yb = xb.to(DEVICE), yb.to(DEVICE)
        opt.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward(); opt.step()

    val_acc = batch_acc(val_dl)
    print(f"epoch {epoch+1:02d}  val_acc={val_acc:.3f}")

    if val_acc > best_val:
        best_val = val_acc; wait=0
        best_state = model.state_dict()
    else:
        wait += 1
        if wait == patience:
            print("early stop"); break

# load best weights
model.load_state_dict(best_state)

# ============================================================
# 4.  final metrics & confusion matrix
# ============================================================
def preds_and_labels(dl):
    model.eval(); P=[]; Y=[]
    with torch.no_grad():
        for xb,yb in dl:
            p = model(xb.to(DEVICE)).argmax(1).cpu()
            P.append(p); Y.append(yb)
    return torch.cat(P).numpy(), torch.cat(Y).numpy()

p_train,y_train = preds_and_labels(train_dl)
p_val,  y_val   = preds_and_labels(val_dl)
p_test, y_test  = preds_and_labels(test_dl)

for name,pred,truth in [("train",p_train,y_train),
                        ("val",  p_val,  y_val),
                        ("test", p_test, y_test)]:
    acc = (pred==truth).mean()
    f1  = f1_score(truth, pred)
    print(f"{name:5s}: acc={acc:.3f}  F1={f1:.3f}")

cm = confusion_matrix(y_test, p_test)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["stable","unstable"],
            yticklabels=["stable","unstable"])
plt.title("Confusion matrix – test set"); plt.show()

"""**The Main Model: The Fourier Neural Operator**"""

# ============================================================
# 2-D FNO
# 0 · imports
# ============================================================
import h5py, torch, numpy as np, matplotlib.pyplot as plt
from torch.utils.data import TensorDataset, DataLoader
from neuralop.models import FNO
import torch.nn as nn

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("using", DEVICE)

# ============================================================
# 1 · load data   (α β ζ₀  →  features   |   state → targets)
# ============================================================
with h5py.File("master_1000.h5", "r") as H:
    Pfull     = H["params"][:]                    # (N,10)
    #X_raw     = Pfull[:, 1:4].astype("float32")   # α,β,ζ₀
    X_raw     = Pfull[:, [0, 1, 2]].astype("float32")
    Y_raw     = H["state"][:].astype("float32")   # (N,7,100)
    t_grid    = H["t"][:]
    idx_train = H["idx_train"][:]
    idx_val   = H["idx_val"][:]
    idx_test  = H["idx_test"][:]
    labels    = H["label"][:]

# ---------- normalize the 3 scalars ----------
x_mean, x_std = X_raw[idx_train].mean(0), X_raw[idx_train].std(0)
Xn = (X_raw - x_mean) / x_std                     # (N,3)

print(Pfull)
print("Pfull shape :", Pfull.shape)
print("X_raw shape :", X_raw.shape)    # should be (N, 3)
print("Xn   shape  :", Xn.shape)       # should be (N, 3) after normalizing

# ---------- standardize the 7 channels ----------
y_mean = Y_raw[idx_train].mean((0, 2), keepdims=True)   # (1,7,1)
y_std  = Y_raw[idx_train].std( (0, 2), keepdims=True) #+ 1e-6
Y      = (Y_raw - y_mean) / y_std                        # (N,7,100)

# ============================================================
# 2 · reshape to 2-D grid  →  X : (N,5,7,100) ,  Y : (N,7,100)
#    • 3 feature planes  (α,β,ζ₀)  broadcast to 7×100
#    • 2 coordinate planes  (ξ, η)
# ============================================================
N, nGrid = Xn.shape[0], Y.shape[-1]

# broadcast features
feat = np.tile(Xn[:, :, None, None], (1, 1, 7, nGrid)).astype("float32")        # (N,3,7,100)

# coordinate channels
coord_x = np.linspace(0, 1, nGrid, dtype="float32")[None, None, None, :]
coord_x = np.tile(coord_x, (N, 1, 7, 1))                   # (N,1,7,100)

coord_y = np.linspace(0, 1, 7, dtype="float32")[None, None, :, None]
coord_y = np.tile(coord_y, (N, 1, 1, nGrid))               # (N,1,7,100)

# Concatenate feature and coordinate channels

#Xgrid = np.concatenate([feat, coord_x, coord_y], axis=1)   # (N,5,7,100)
Xgrid = feat

#Xgrid = torch.tensor(Xgrid, dtype=torch.float32)
Xgrid  = torch.tensor(feat)
Y     = torch.tensor(Y,     dtype=torch.float32)                  # scaled

def loader(idxs, bs, shuffle=False):
    ds = TensorDataset(Xgrid[idxs], Y[idxs])
    return DataLoader(ds, batch_size=bs, shuffle=shuffle)

train_dl = loader(idx_train, 128, True)
val_dl   = loader(idx_val,   8)
test_dl  = loader(idx_test,  8)

xb, _ = next(iter(loader(idx_train, 4)))
print("batch shape:", xb.shape)          # (4, 3, 7, 100)   ✓
num_phys = Xgrid.shape[1]        # 2 or 3, whatever is really there
print("feeding FNO with", num_phys, "physical channels")

# ============================================================
# 3 · 2-D FNO model (1-D version was also tested)
# ============================================================
model = FNO(
    n_modes             = (128,128),          # α β ζ₀ ξ η  (no auto-grid)
    hidden_channels     = 64,
    in_channels         = num_phys,
    out_channels        = 7,
    n_layers            = 8,

).to(DEVICE)

#!nvidia-smi

optim   = torch.optim.Adam(model.parameters(), lr=3e-3)
loss_fn = nn.MSELoss()

# ============================================================
# 4 · training loop (loss uses .squeeze(2) to drop dummy H-dim)
# ============================================================
best_val = 1e9; patience = 1000; wait = 0
for epoch in range(15):
    # ---- train ------------------------------------------------
    model.train(); running = 0; n = 0
    for xb, yb in train_dl:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optim.zero_grad()
        pred = model(xb).mean(dim=2)          # (B,7,100)
        loss = loss_fn(pred, yb)
        loss.backward(); optim.step()
        running += loss.item()*len(xb); n += len(xb)
    train_mse = running / n

    # ---- validation ------------------------------------------
    model.eval(); vloss = 0; n = 0
    with torch.no_grad():
        for xb, yb in val_dl:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            #vloss += loss_fn(model(xb).squeeze(2), yb).item()*len(xb)
            vloss += loss_fn(model(xb).mean(dim=2), yb).item()*len(xb)
            n += len(xb)
    vloss /= n
    print(f"ep {epoch:03d}  train={train_mse:.2e}  val={vloss:.2e}")

    if vloss < best_val:
        best_val, wait, best_state = vloss, 0, model.state_dict()
    else:
        wait += 1
        if wait == patience:
            print("early stop"); break

model.load_state_dict(best_state)


# ============================================================
# helper · FNO2d → trajectory generator
# ============================================================
@torch.no_grad()
def fno2d_predict(alpha: float, beta: float, zeta0: float,
                  *,
                  H: int = 7,                    # height used in training
                  t_grid=t_grid,                 # (100,) array from file
                  x_mu=x_mean, x_sig=x_std,      # scalars’ training stats
                  y_mu=y_mean.squeeze(),         # (7,)  training mean
                  y_sig=y_std.squeeze(),         # (7,)  training st-dev
                  model=model, device=DEVICE):
    """
    Returns a (7, 100) ndarray with
    [R, V, ρg, ρτ, ρs, T, m] on the original time grid.
    """
    # 1 · normalize the three input scalars exactly as in training
    x_phys   = np.asarray([alpha, beta, zeta0], dtype="float32")   # (3,)
    x_norm   = (x_phys - x_mu) / x_sig                            # (3,)
    # 2 · broadcast over the 7×100 lattice  → shape (1,3,7,100)
    W        = len(t_grid)
    feat     = np.tile(x_norm[:, None, None], (1, H, W))          # (3,7,100)
    x_tensor = torch.tensor(feat[None], dtype=torch.float32,
                            device=device)                        # (1,3,7,100)
    # 3 · forward pass through FNO2d and collapse the dummy height
    y_norm   = model(x_tensor).mean(dim=2).cpu().squeeze(0).numpy()  # (7,100)
    # 4 · de-normalize back to physical units
    y_phys   = y_norm * y_sig[:, None] + y_mu[:, None]             # (7,100)
    return y_phys

# ============================================================
# 5 · test-set MSE + denormalized example plot
# ============================================================
model.eval(); test_mse = 0; n = 0
with torch.no_grad():
    for xb, yb in test_dl:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        test_mse += loss_fn(model(xb).mean(dim=2), yb).item()*len(xb)
        n += len(xb)
test_mse /= n
print("test MSE (normalized):", test_mse)

# ============================================================
# 6 · Saliency-map utilities
# ============================================================
@torch.no_grad()
def _prep_input(alpha, beta, zeta0, *, H=7):
    """Return a (1, 3, 7, 100) tensor with grads enabled on the 3 scalars."""
    x_phys  = np.asarray([alpha, beta, zeta0], dtype="float32")
    x_norm  = (x_phys - x_mean) / x_std                       # (3,)
    feat    = np.tile(x_norm[:, None, None], (1, H, len(t_grid)))  # (3,7,100)
    x_tens  = torch.tensor(feat[None], dtype=torch.float32,
                           device=DEVICE, requires_grad=True)
    return x_tens

def saliency(alpha, beta, zeta0,
             *, collapse=True, functional=lambda y: y[2].max()):
    """
    Gradient d(functional)/d[α,β,ζ₀].
      • functional: scalar of y_hat to differentiate (default: peak ρ_g)
      • collapse  : if True, uses .mean(dim=2) to drop dummy height
    Returns ndarray (3, 7, 100) of gradients.
    """
    model.eval()
    x_tens = _prep_input(alpha, beta, zeta0)
    y_hat  = model(x_tens)
    if collapse:
        y_hat = y_hat.mean(dim=2)      # (1,7,100)
    L = functional(y_hat.squeeze(0))   # scalar
    # -- backward
    model.zero_grad(set_to_none=True)
    L.backward()
    grad = x_tens.grad.detach().cpu().squeeze(0).numpy()  # (3,7,100)
    return grad


# ============================================================
# 7 · Sobol indices helper
# ============================================================

from SALib.sample import saltelli
from SALib.analyze import sobol
#from SALib.sample import sobol

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]
par_names = [r"α", r"β", r"ζ₀"]

def sobol_qoi(channel="ρg[τ]", stat="max",
              *, N=2000, batch_size=512,
              model_predict=fno2d_predict):
    """
    Compute first- & total-order Sobol' indices for a scalar QoI.
      channel : str or int   – which output variable
      stat    : "max" | "final" | "integral" | callable(traj)->scalar
      N       : base sample count for Saltelli (total ≈ 8 N)
    Returns dicts  S1 , ST  keyed by parameter names.
    """
    # ── resolve channel index
    if isinstance(channel, str):
        channel = var_names.index(channel)
    chan_name = var_names[channel]

    # ── choose how to turn a 100-point curve into one scalar
    if isinstance(stat, str):
        if stat == "max":
            f = lambda y: y[channel].max()
        elif stat == "final":
            f = lambda y: y[channel, -1]
        elif stat == "integral":
            f = lambda y: y[channel].sum()
        else:
            raise ValueError("unknown stat")
    elif callable(stat):
        f = stat
    else:
        raise TypeError("stat must be str or callable")

    # ── SALib problem definition in *normalized* coordinates
    problem = {
        "num_vars": 3,
        "names":    par_names,
        "bounds":   [[-3, 3]]*3          # ±3 σ after normalization
    }

    # ── draw quasi-Monte-Carlo sample
    P = saltelli.sample(problem, N, calc_second_order=False)
    #P = sobol.sample(problem, N, calc_second_order=False)

    # ── evaluate QoI in mini-batches
    outs = []
    for i in range(0, len(P), batch_size):
        batch = P[i:i+batch_size]
        scalars = []
        for trio in batch:
            α, β, ζ = trio * x_std + x_mean          # de-norm
            traj    = model_predict(α, β, ζ)          # (7,100)
            scalars.append(f(traj))
        outs.append(np.asarray(scalars, "float32"))
    Y = np.concatenate(outs)

    # ── Sobol' analysis
    Si = sobol.analyze(problem, Y, calc_second_order=False,
                       print_to_console=False)
    S1 = dict(zip(par_names, Si["S1"]))
    ST = dict(zip(par_names, Si["ST"]))
    return S1, ST, chan_name, stat

# ---- plot one sample (denormalized) ------------------------
idx  = int(idx_test[0])
x_in = Xgrid[idx:idx+1].to(DEVICE)
with torch.no_grad():
    #y_pred_norm = model(x_in).squeeze(2).cpu()[0]
    y_pred_norm = model(x_in).mean(dim=2).cpu()[0]

y_true = Y_raw[idx]                                   # original scale
y_std_reshaped  = y_std.squeeze()[:, None]
y_mean_reshaped = y_mean.squeeze()[:, None]
y_pred = (y_pred_norm * y_std_reshaped) + y_mean_reshaped

#plt.figure(figsize=(5,4))
#plt.plot(t_grid, y_true[0],  label="R true")
#plt.plot(t_grid, y_pred[0], '--', label="R pred")
#plt.legend(); plt.grid(True)
#plt.title("sample trajectory – true vs 2-D FNO prediction")
#plt.show()

# -------- plot all 7 variables ------------------------------

fig, axes = plt.subplots(3, 3, figsize=(20, 13))
axes = axes.ravel()
for i in range(7):
    ax = axes[i]
    ax.plot(t_grid, y_true[i], label="true")
    ax.plot(t_grid, y_pred[i], "--", label="pred")
    ax.set_title(var_names[i]); ax.grid(False); ax.legend()
axes[7].axis("off"); axes[8].axis("off")
fig.suptitle(f"Evolutions of State Variables with Space Parameters \nα={Pfull[idx,0]:.4f}  β={Pfull[idx,1]:.4f}  ζ0={Pfull[idx,2]:.4f}")
#fig.suptitle(f"sample idx {idx}")
fig.tight_layout()
plt.show()

# ------------------------------------------------------------
# plot ALL 7 variables  (each in its own subplot)
# ------------------------------------------------------------
# ---- plot one sample (denormalize) ----
idx  = 16584 #int(idx_test[0]) 20
x_in = Xgrid[idx:idx+1].to(DEVICE)
with torch.no_grad():
    y_pred_norm = model(x_in).mean(dim=2).cpu()[0]

y_true = Y_raw[idx]                                      # original scale
# Reshape y_std and y_mean to allow broadcasting across the time dimension
y_std_reshaped = y_std.squeeze()[:, None]  # Shape becomes (7, 1)
y_mean_reshaped = y_mean.squeeze()[:, None] # Shape becomes (7, 1)

# Perform denormalization
y_pred = (y_pred_norm * y_std_reshaped) + y_mean_reshaped

#plt.figure(figsize=(5,4))
#plt.plot(t_grid, y_true[0],  label="R true")
#plt.plot(t_grid, y_pred[0], '--', label="R pred")
#plt.legend(); plt.grid(True)
#plt.title("sample trajectory – true vs FNO prediction")
#plt.show()


var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]   # optional labels

fig, axes = plt.subplots(3, 3, figsize=(20, 15), dpi=600)        # 3×3 grid (last 2 empty)
axes = axes.ravel()

for i in range(7):

    ax = axes[i]

    line_true = ax.plot(t_grid, y_true[i], label="TRUE", color="black", linewidth=2)[0]
    line_fno = ax.plot(t_grid, y_pred[i], "--", label="FNO", color="blue", linewidth=2, linestyle="--")[0]

    ax.set_xlim(t_grid.min(), t_grid.max())
    ax.set_ylim(ax.get_ylim()) # Locks current auto-scaled Y limits

    ax.axhline(0, color="gray", linestyle="--", linewidth=0.8, alpha=0.7)
    ax.axvline(50000, color="grey", linestyle="--", linewidth=0.8, alpha=0.7)
    ax.axvline(350000, color="grey", linestyle="--", linewidth=0.8, alpha=0.7)


    #ax.yaxis.set_major_formatter(FormatStrFormatter('%.3f'))
    ax.ticklabel_format(axis='y', style='sci', scilimits=(0,0), useMathText=True)
    ax.yaxis.get_offset_text().set_fontsize(11)


    #ax.legend()
    ax.grid(False)
    ax.set_ylabel(var_names[i], fontsize=14)
    ax.set_xlabel("τ", fontsize=14)

    ax.tick_params(axis='both', which='major', labelsize=12, width=1.5, length=6, direction='in')
    ax.xaxis.set_minor_locator(AutoMinorLocator(5))
    ax.yaxis.set_minor_locator(AutoMinorLocator(5))
    ax.tick_params(axis='both', which='minor', length=3, width=1, direction='in')


legend_box = axes[7]
legend_box.axis('off')
legend_box.legend(
    [line_true, line_fno],
    ["TRUE", "FNO"],
    loc="center",
    fontsize=16,
    frameon=True)

axes[8].axis("off")

fig.suptitle(f"Evolutions of State Variables: True Values vs. FNO Predictions \n", fontsize=18, fontweight='bold')

save_directory = '/content/drive/MyDrive/'
file_path = os.path.join(save_directory, 'my_plot.pdf')

fig.tight_layout()
#plt.savefig('my_plot.pdf', format='pdf')
plt.savefig(file_path, format='pdf', bbox_inches='tight')
plt.show()

print(f"Paramter space values \nα={Pfull[idx,0]:.4f}  β={Pfull[idx,1]:.4f}  ζ0={Pfull[idx,2]:.4f}")

# ================================================================================
# The model is trained! Input values for α, β, ζ0 to generate sample trajectories
# ================================================================================


α, β, ζ0 = 0.399, -0.2667, 0.1
traj = fno2d_predict(α, β, ζ0)          # (7, 100)

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]
cpact = traj[6]/traj[0]


fig, axes = plt.subplots(3, 3, figsize=(15, 10))        # 3×3 grid (last 2 empty)
axes = axes.ravel()

for i in range(7):
    ax = axes[i]
    ax.plot(t_grid, traj[i], label="pred")
    ax.set_title(var_names[i])
    ax.grid(True)

axes[7].axis("off"); axes[8].axis("off")               # blank unused subplots
fig.suptitle(f"α={α:.3f}, β={β:.3f}, ζ₀={ζ0:.2e}")
fig.tight_layout()
plt.show()

plt.plot(t_grid, cpact, label="compactness")
plt.xlabel("t"); plt.grid(); plt.legend()
plt.title(f"α={α:.3f}, β={β:.3f}, ζ₀={ζ0:.2e}")
plt.show()

# ===================================================================================================================
# Saliency analysis: the plot shows the derivative of a dynamical variable with respect to one of the space parameters
# ===================================================================================================================

# Pick a point in parameter space
α, β, ζ0 = 0.5816, -0.1109, 0.1105
G = saliency(α, β, ζ0)                # (3, 7, 100)

# Visualize |∂ρg / ∂α| as a heat-map
plt.figure(figsize=(12,8))
plt.imshow(np.abs(G[0, 2][None, :]), aspect='auto',
           extent=[t_grid[0], t_grid[-1], 0, 1])
plt.colorbar(label=r"|∂ρg / ∂α|")
plt.xlabel("time"); plt.yticks([])
plt.title("Saliency of α on ρg(t)")
plt.show()

#   Saliency-plot helpers

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]
par_names = [r"α", r"β", r"ζ₀"]

def plot_saliency_all(G, chan=2):
    """
    Show |∂Y_chan/∂p| for p = α,β,ζ₀  (one row, three panels).
       • G     : gradient tensor (3,7,100) from saliency()
       • chan  : int or str – channel to display
    """
    if isinstance(chan, str):
        chan = var_names.index(chan)
    fig, axs = plt.subplots(1, 3, figsize=(12, 5), sharey=True)
    for i, ax in enumerate(axs):
        im = ax.imshow(np.abs(G[i, chan][None, :]),
                       aspect='auto', origin='lower',
                       extent=[t_grid[0], t_grid[-1], 0, 1])
        ax.set_title(fr"$|{{\partial {var_names[chan]}}}/{{\partial {par_names[i]}}}|$")
        ax.set_xlabel("time"); ax.set_yticks([])
        fig.colorbar(im, ax=ax, pad=0.01)
    fig.suptitle(f"Saliency of {var_names[chan]} to each parameter")
    plt.tight_layout(); plt.show()

def plot_saliency_grid(G):
    """
    7 × 3 grid: rows = output channels, cols = α,β,ζ₀ sensitivities.
    """
    fig, axs = plt.subplots(7, 3, figsize=(12, 5), sharex=True, sharey='row')
    for r in range(7):
        for c in range(3):
            ax = axs[r, c]
            im = ax.imshow(np.abs(G[c, r][None, :]),
                           aspect='auto', origin='lower',
                           extent=[t_grid[0], t_grid[-1], 0, 1])
            if r == 0: ax.set_title(par_names[c])
            if c == 0: ax.set_ylabel(var_names[r])
            if r == 6: ax.set_xlabel("time")
    fig.colorbar(im, ax=axs, location='right', pad=0.01,
                 label=r"$|∂Y/∂p|$")
    fig.suptitle("Saliency heat-maps for all channels")
    plt.tight_layout(); plt.show()

α, β, ζ0 = 0.5816, -0.1109, 0.1105
G = saliency(α, β, ζ0)        # (3, 7, 100)

# show α,β,ζ₀ sensitivities
plot_saliency_all(G, chan=1)   # or chan=2

# 3 full 7 × 3 overview
#plot_saliency_grid(G)

# Quantify how α, β, ζ₀ propagate into each field. Useful for experimental design.
# global‐variance sensitivity measures
# S1: fraction of the global variance of the field that is explained by parameter acting alone
# ST: fraction of the variance that disappears if you could fix the parameter:
      # It therefore includes all higher-order interactions that contain the parameter (alpha, beta, zeta)
# Statistical reading:
  #max: How much can this variable peak out? ex. max → sensitivity of peak gas density.
  #final: What decides the end-state value? final → sensitivity of gas density at the last time-step.
  #integral: Which parameters drive the total accumulated effect/flux/energy? sensitivity of total gas emitted over the whole simulation.

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]

S1, ST, ch, stat_used = sobol_qoi(channel=var_names[1], stat="max", N=1024)
print(f"Sobol, QoI = {stat_used}({ch})")
print("First-order :", S1)
print("Total-order :", ST)

def sobol_bar(S1, ST, title="Sobol indices"):
    fig, ax = plt.subplots(figsize=(4,3), dpi=600)
    ax.bar(range(3), [S1[k] for k in par_names], label="Parameter Contribution")
    ax.bar(range(3), [ST[k]-S1[k] for k in par_names], bottom=[S1[k] for k in par_names],
           alpha=0.4, label="Residual Contribution")
    ax.set_xticks(range(3)); ax.set_xticklabels(par_names)
    ax.set_ylabel("fraction of variance"); ax.set_ylim(0,1)
    ax.set_title(title); ax.legend(); plt.show()

sobol_bar(S1, ST, title=f"QoI: {stat_used}({ch})")

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]

for s in ["max", "final", "integral"]:
    S1, ST, ch, _ = sobol_qoi(var_names[0], stat=s, N=1024)
    sobol_bar(S1, ST, title=f"variation attribution – {s}({ch})")

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]

for s in ["max", "final", "integral"]:
    S1, ST, ch, _ = sobol_qoi(var_names[1], stat=s, N=1024)
    sobol_bar(S1, ST, title=f"variation attribution – {s}({ch})")

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]

for s in ["max", "final", "integral"]:
    S1, ST, ch, _ = sobol_qoi(var_names[2], stat=s, N=1024)
    sobol_bar(S1, ST, title=f"variation attribution – {s}({ch})")

var_names = ["R[τ]", "V[τ]", "ρg[τ]", "ρτ[τ]", "ρs[τ]", "T[τ]", "m[τ]"]

for s in ["max", "final", "integral"]:
    S1, ST, ch, _ = sobol_qoi(var_names[5], stat=s, N=1024)
    sobol_bar(S1, ST, title=f"variation attribution – {s}({ch})")

#   Extra statistics: dominant frequency & phase shift

import numpy as np
from functools import partial

_dt = float(t_grid[1] - t_grid[0])          # sampling interval (sec)
_N  = len(t_grid)

def _dominant_bin(sig):
    """Return index of largest magnitude FFT bin (excluding DC)."""
    yf   = np.fft.rfft(sig - sig.mean())    # remove mean for clarity
    idx  = np.argmax(np.abs(yf[1:])) + 1    # +1 to skip DC bin 0
    return idx, yf

def dominant_freq_stat(ch):
    """callable for sobol_qoi → dominant frequency [Hz] of channel ch."""
    def _stat(traj):
        idx, _ = _dominant_bin(traj[ch])
        freqs  = np.fft.rfftfreq(_N, _dt)
        return freqs[idx]
    return _stat

def phase_stat(ch):
    """callable for sobol_qoi → phase (rad) of dominant component."""
    def _stat(traj):
        idx, yf = _dominant_bin(traj[ch])
        return np.angle(yf[idx])
    return _stat


# dominant frequency of R
S1, ST, ch, _ = sobol_qoi(channel="R[τ]",
                          stat=dominant_freq_stat(var_names.index("R[τ]")),
                          N=1024)
sobol_bar(S1, ST, title=r"Dominant-freq (R[τ])")

# phase angle of R
S1, ST, ch, _ = sobol_qoi(channel="R[τ]",
                          stat=phase_stat(var_names.index("R[τ]")),
                          N=1024)
sobol_bar(S1, ST, title=r"Phase of dominant oscillation (R[τ])")